### ISSUE TITLE
side panel issue

### ISSUE THREAD

**Issue by c02y** [drannex42/vivaldi-mods#4]
Currently, the vertical tabs pane covers the side panel, not able to use side panel.

**Comment by macleod-ee** [comment]
I stopped using Vivaldi about a year ago when they introduced an ill designed second tab bar, instead of implementing a tree style tab system, and there seemingly random UI and CSS changes that broke the extension every update requiring heavy reworks. 

I have since switched to Firefox and have been updating a [far more powerful, simpler,  and usable design using Sideberry on Firefox](https://github.com/drannex42/linux-utils/tree/main/firefox) that _a lot_ of people have started using. 

I'm afraid anything Vivaldi related I will not be able to help on.

**Comment by c02y** [comment]
Thanks for the link. I'll check it out.
